spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
com:
  mysql:
    cj:
      jdbc:
        Driver:
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F
      expiration: 6000000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
